"""Every Huudis feature route, one method each — generated by apigen from
backend/openapi.json. Do not edit by hand; regenerate after the API changes.

Reach them as ``client.api.<area>_<action>(...)``. Each call goes through the
client's own ``_apigen_request`` (its sign-in and response envelope).
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


class GeneratedApi:
    """All 111 feature routes of the Huudis API."""

    def __init__(self, client: Any) -> None:
        self._client = client

    def _call(self, method: str, path: str, query: Dict[str, Any], body: Optional[Dict[str, Any]]) -> Any:
        query = {k: v for k, v in query.items() if v is not None}
        return self._client._apigen_request(method, path, query=query or None, body=body)

    def account_audit(self, *, limit: Optional[int] = None, cursor: Optional[str] = None, event: Optional[str] = None, outcome: Optional[str] = None, since: Optional[str] = None, until: Optional[str] = None) -> Any:
        """List audit (GET /api/v1/account/audit)."""
        return self._call("GET", f"/api/v1/account/audit", {"limit": limit, "cursor": cursor, "event": event, "outcome": outcome, "since": since, "until": until}, None)

    def account_billing(self) -> Any:
        """/billing surface for the Huudis dashboard. (GET /api/v1/account/billing)."""
        return self._call("GET", f"/api/v1/account/billing", {}, None)

    def account_billing_cancel(self) -> Any:
        """Create a cancel (POST /api/v1/account/billing/cancel)."""
        return self._call("POST", f"/api/v1/account/billing/cancel", {}, None)

    def account_billing_checkout(self, *, tier: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a checkout (POST /api/v1/account/billing/checkout).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        tier: one of pro, business, scale"""
        payload: Dict[str, Any] = dict(json_body or {})
        if tier is not None:
            payload["tier"] = tier
        if "tier" not in payload:
            raise ValueError("account_billing_checkout needs tier")
        return self._call("POST", f"/api/v1/account/billing/checkout", {}, payload)

    def account_billing_invoices(self) -> Any:
        """List invoices (GET /api/v1/account/billing/invoices)."""
        return self._call("GET", f"/api/v1/account/billing/invoices", {}, None)

    def account_billing_plans(self) -> Any:
        """Public to authenticated sessions — no account scope needed since every user sees the same plans. (GET /api/v1/account/billing/plans)."""
        return self._call("GET", f"/api/v1/account/billing/plans", {}, None)

    def account_billing_usage(self) -> Any:
        """List usage (GET /api/v1/account/billing/usage)."""
        return self._call("GET", f"/api/v1/account/billing/usage", {}, None)

    def account_cancel_deletion(self) -> Any:
        """Create a cancel deletion (POST /api/v1/account/cancel-deletion)."""
        return self._call("POST", f"/api/v1/account/cancel-deletion", {}, None)

    def account_connected_apps(self) -> Any:
        """Signal = `RefreshToken`, not `OidcConsent`. (GET /api/v1/account/connected-apps)."""
        return self._call("GET", f"/api/v1/account/connected-apps", {}, None)

    def account_connected_apps_revoke(self, client_id: str) -> Any:
        """Revoke every live refresh-token family this user holds for the client. (POST /api/v1/account/connected-apps/{clientId}/revoke)."""
        return self._call("POST", f"/api/v1/account/connected-apps/{_q(client_id)}/revoke", {}, None)

    def account_create_webhook_subscriptions(self, *, url: Optional[str] = None, events: Optional[List[Any]] = None, description: Optional[str] = None, active: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a webhook subscription (POST /api/v1/account/webhook-subscriptions).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if url is not None:
            payload["url"] = url
        if events is not None:
            payload["events"] = events
        if description is not None:
            payload["description"] = description
        if active is not None:
            payload["active"] = active
        if "url" not in payload:
            raise ValueError("account_create_webhook_subscriptions needs url")
        if "events" not in payload:
            raise ValueError("account_create_webhook_subscriptions needs events")
        return self._call("POST", f"/api/v1/account/webhook-subscriptions", {}, payload)

    def account_create_workspaces(self, *, name: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a workspace (POST /api/v1/account/workspaces).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if "name" not in payload:
            raise ValueError("account_create_workspaces needs name")
        return self._call("POST", f"/api/v1/account/workspaces", {}, payload)

    def account_delete(self, *, password: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Delete account (DELETE /api/v1/account).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if password is not None:
            payload["password"] = password
        return self._call("DELETE", f"/api/v1/account", {}, payload)

    def account_delete_connected_apps(self, id_: str) -> Any:
        """Legacy consent-id path. (DELETE /api/v1/account/connected-apps/{id})."""
        return self._call("DELETE", f"/api/v1/account/connected-apps/{_q(id_)}", {}, None)

    def account_delete_linked_accounts(self, provider: str) -> Any:
        """Delete a linked account (DELETE /api/v1/account/linked-accounts/{provider})."""
        return self._call("DELETE", f"/api/v1/account/linked-accounts/{_q(provider)}", {}, None)

    def account_delete_social_providers(self, provider: str) -> Any:
        """Delete a social provider (DELETE /api/v1/account/social-providers/{provider})."""
        return self._call("DELETE", f"/api/v1/account/social-providers/{_q(provider)}", {}, None)

    def account_delete_webhook_subscriptions(self, id_: str) -> Any:
        """Delete a webhook subscription (DELETE /api/v1/account/webhook-subscriptions/{id})."""
        return self._call("DELETE", f"/api/v1/account/webhook-subscriptions/{_q(id_)}", {}, None)

    def account_email_change(self, *, email: Optional[str] = None, password: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an email change (POST /api/v1/account/email-change).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if email is not None:
            payload["email"] = email
        if password is not None:
            payload["password"] = password
        if "email" not in payload:
            raise ValueError("account_email_change needs email")
        if "password" not in payload:
            raise ValueError("account_email_change needs password")
        return self._call("POST", f"/api/v1/account/email-change", {}, payload)

    def account_get_webhook_subscriptions(self, id_: str) -> Any:
        """Get a webhook subscription (GET /api/v1/account/webhook-subscriptions/{id})."""
        return self._call("GET", f"/api/v1/account/webhook-subscriptions/{_q(id_)}", {}, None)

    def account_linked_accounts(self) -> Any:
        """List linked accounts (GET /api/v1/account/linked-accounts)."""
        return self._call("GET", f"/api/v1/account/linked-accounts", {}, None)

    def account_list(self) -> Any:
        """List account (GET /api/v1/account)."""
        return self._call("GET", f"/api/v1/account", {}, None)

    def account_password_change(self, *, current_password: Optional[str] = None, new_password: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a password change (POST /api/v1/account/password-change).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if current_password is not None:
            payload["currentPassword"] = current_password
        if new_password is not None:
            payload["newPassword"] = new_password
        if "newPassword" not in payload:
            raise ValueError("account_password_change needs new_password")
        return self._call("POST", f"/api/v1/account/password-change", {}, payload)

    def account_schedule_deletion(self, *, password: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Self-serve soft-delete: stamps a 30-day grace marker. (POST /api/v1/account/schedule-deletion).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if password is not None:
            payload["password"] = password
        return self._call("POST", f"/api/v1/account/schedule-deletion", {}, payload)

    def account_services(self) -> Any:
        """List services (GET /api/v1/account/services)."""
        return self._call("GET", f"/api/v1/account/services", {}, None)

    def account_services_disable(self, *, services: Optional[List[Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a disable (POST /api/v1/account/services/disable).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if services is not None:
            payload["services"] = services
        if "services" not in payload:
            raise ValueError("account_services_disable needs services")
        return self._call("POST", f"/api/v1/account/services/disable", {}, payload)

    def account_services_enable(self, *, services: Optional[List[Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an enable (POST /api/v1/account/services/enable).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if services is not None:
            payload["services"] = services
        if "services" not in payload:
            raise ValueError("account_services_enable needs services")
        return self._call("POST", f"/api/v1/account/services/enable", {}, payload)

    def account_sessions(self) -> Any:
        """List sessions (GET /api/v1/account/sessions)."""
        return self._call("GET", f"/api/v1/account/sessions", {}, None)

    def account_sessions_revoke(self, id_: str) -> Any:
        """Revoke a session (POST /api/v1/account/sessions/{id}/revoke)."""
        return self._call("POST", f"/api/v1/account/sessions/{_q(id_)}/revoke", {}, None)

    def account_sessions_revoke_all(self) -> Any:
        """Create a revoke all (POST /api/v1/account/sessions/revoke-all)."""
        return self._call("POST", f"/api/v1/account/sessions/revoke-all", {}, None)

    def account_set_social_providers(self, provider: str, *, client_id: Optional[str] = None, secret: Optional[str] = None, redirect_uri: Optional[str] = None, team_id: Optional[str] = None, key_id: Optional[str] = None, enabled: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Replace a social provider (PUT /api/v1/account/social-providers/{provider}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if client_id is not None:
            payload["clientId"] = client_id
        if secret is not None:
            payload["secret"] = secret
        if redirect_uri is not None:
            payload["redirectUri"] = redirect_uri
        if team_id is not None:
            payload["teamId"] = team_id
        if key_id is not None:
            payload["keyId"] = key_id
        if enabled is not None:
            payload["enabled"] = enabled
        if "clientId" not in payload:
            raise ValueError("account_set_social_providers needs client_id")
        return self._call("PUT", f"/api/v1/account/social-providers/{_q(provider)}", {}, payload)

    def account_social_providers(self) -> Any:
        """List social providers (GET /api/v1/account/social-providers)."""
        return self._call("GET", f"/api/v1/account/social-providers", {}, None)

    def account_update(self, *, name: Optional[str] = None, locale: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update account (PATCH /api/v1/account).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if locale is not None:
            payload["locale"] = locale
        return self._call("PATCH", f"/api/v1/account", {}, payload)

    def account_update_webhook_subscriptions(self, id_: str, *, url: Optional[str] = None, events: Optional[List[Any]] = None, description: Optional[str] = None, active: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a webhook subscription (PATCH /api/v1/account/webhook-subscriptions/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if url is not None:
            payload["url"] = url
        if events is not None:
            payload["events"] = events
        if description is not None:
            payload["description"] = description
        if active is not None:
            payload["active"] = active
        return self._call("PATCH", f"/api/v1/account/webhook-subscriptions/{_q(id_)}", {}, payload)

    def account_update_workspaces(self, id_: str, *, name: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a workspace (PATCH /api/v1/account/workspaces/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if "name" not in payload:
            raise ValueError("account_update_workspaces needs name")
        return self._call("PATCH", f"/api/v1/account/workspaces/{_q(id_)}", {}, payload)

    def account_webhook_subscriptions(self) -> Any:
        """List webhook subscriptions (GET /api/v1/account/webhook-subscriptions)."""
        return self._call("GET", f"/api/v1/account/webhook-subscriptions", {}, None)

    def account_webhook_subscriptions_deliveries(self, id_: str, *, limit: Optional[Any] = None, status: Optional[Any] = None) -> Any:
        """List deliveries (GET /api/v1/account/webhook-subscriptions/{id}/deliveries)."""
        return self._call("GET", f"/api/v1/account/webhook-subscriptions/{_q(id_)}/deliveries", {"limit": limit, "status": status}, None)

    def account_webhook_subscriptions_deliveries_replay(self, id_: str) -> Any:
        """Replay a delivery (POST /api/v1/account/webhook-subscriptions/deliveries/{id}/replay)."""
        return self._call("POST", f"/api/v1/account/webhook-subscriptions/deliveries/{_q(id_)}/replay", {}, None)

    def account_webhook_subscriptions_events_catalog(self) -> Any:
        """List catalog (GET /api/v1/account/webhook-subscriptions/events/catalog)."""
        return self._call("GET", f"/api/v1/account/webhook-subscriptions/events/catalog", {}, None)

    def account_webhook_subscriptions_rotate_secret(self, id_: str) -> Any:
        """Rotate secret a webhook subscription (POST /api/v1/account/webhook-subscriptions/{id}/rotate-secret)."""
        return self._call("POST", f"/api/v1/account/webhook-subscriptions/{_q(id_)}/rotate-secret", {}, None)

    def account_workspaces(self) -> Any:
        """List workspaces (GET /api/v1/account/workspaces)."""
        return self._call("GET", f"/api/v1/account/workspaces", {}, None)

    def account_workspaces_cancel_deletion(self, id_: str) -> Any:
        """Cancel deletion a workspace (POST /api/v1/account/workspaces/{id}/cancel-deletion)."""
        return self._call("POST", f"/api/v1/account/workspaces/{_q(id_)}/cancel-deletion", {}, None)

    def account_workspaces_members(self, id_: str) -> Any:
        """Additive, read-only. (GET /api/v1/account/workspaces/{id}/members)."""
        return self._call("GET", f"/api/v1/account/workspaces/{_q(id_)}/members", {}, None)

    def account_workspaces_schedule_deletion(self, id_: str) -> Any:
        """Owner-only soft-delete: stamps a 30-day grace marker on the workspace. (POST /api/v1/account/workspaces/{id}/schedule-deletion)."""
        return self._call("POST", f"/api/v1/account/workspaces/{_q(id_)}/schedule-deletion", {}, None)

    def account_workspaces_switch(self, id_: str) -> Any:
        """Switch a workspace (POST /api/v1/account/workspaces/{id}/switch)."""
        return self._call("POST", f"/api/v1/account/workspaces/{_q(id_)}/switch", {}, None)

    def app_overview(self) -> Any:
        """One row per OIDC client that has ever minted a refresh token: distinct users, 30-day signups, last signup + last activity. (GET /api/v1/app/overview)."""
        return self._call("GET", f"/api/v1/app/overview", {}, None)

    def app_stats(self, *, q: Optional[str] = None, status: Optional[str] = None, limit: Optional[int] = None, client_id: Optional[str] = None) -> Any:
        """List stats (GET /api/v1/app/stats)."""
        return self._call("GET", f"/api/v1/app/stats", {"q": q, "status": status, "limit": limit, "clientId": client_id}, None)

    def app_users(self, *, q: Optional[str] = None, status: Optional[str] = None, limit: Optional[int] = None, client_id: Optional[str] = None) -> Any:
        """List users (GET /api/v1/app/users)."""
        return self._call("GET", f"/api/v1/app/users", {"q": q, "status": status, "limit": limit, "clientId": client_id}, None)

    def app_workspaces(self, *, ids: str) -> Any:
        """List workspaces (GET /api/v1/app/workspaces)."""
        return self._call("GET", f"/api/v1/app/workspaces", {"ids": ids}, None)

    def authz_assume_role(self, *, role_id: Optional[str] = None, session_name: Optional[str] = None, duration_seconds: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an assume role (POST /api/v1/authz/assume-role).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if role_id is not None:
            payload["roleId"] = role_id
        if session_name is not None:
            payload["sessionName"] = session_name
        if duration_seconds is not None:
            payload["durationSeconds"] = duration_seconds
        if "roleId" not in payload:
            raise ValueError("authz_assume_role needs role_id")
        return self._call("POST", f"/api/v1/authz/assume-role", {}, payload)

    def authz_check(self, *, principal: Optional[Dict[str, Any]] = None, action: Optional[str] = None, resource: Optional[str] = None, context: Optional[Dict[str, Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a check (POST /api/v1/authz/check).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if principal is not None:
            payload["principal"] = principal
        if action is not None:
            payload["action"] = action
        if resource is not None:
            payload["resource"] = resource
        if context is not None:
            payload["context"] = context
        if "principal" not in payload:
            raise ValueError("authz_check needs principal")
        if "action" not in payload:
            raise ValueError("authz_check needs action")
        if "resource" not in payload:
            raise ValueError("authz_check needs resource")
        return self._call("POST", f"/api/v1/authz/check", {}, payload)

    def authz_whoami(self) -> Any:
        """Session-auth health ping so dashboard can verify reachability. (GET /api/v1/authz/whoami)."""
        return self._call("GET", f"/api/v1/authz/whoami", {}, None)

    def iam_access_keys(self, *, principal_type: str, principal_id: str) -> Any:
        """List access keys (GET /api/v1/iam/access-keys)."""
        return self._call("GET", f"/api/v1/iam/access-keys", {"principalType": principal_type, "principalId": principal_id}, None)

    def iam_access_keys_revoke(self, id_: str) -> Any:
        """Revoke an access key (POST /api/v1/iam/access-keys/{id}/revoke)."""
        return self._call("POST", f"/api/v1/iam/access-keys/{_q(id_)}/revoke", {}, None)

    def iam_assumed_sessions(self) -> Any:
        """List assumed sessions (GET /api/v1/iam/assumed-sessions)."""
        return self._call("GET", f"/api/v1/iam/assumed-sessions", {}, None)

    def iam_assumed_sessions_revoke(self, id_: str) -> Any:
        """Revoke an assumed session (POST /api/v1/iam/assumed-sessions/{id}/revoke)."""
        return self._call("POST", f"/api/v1/iam/assumed-sessions/{_q(id_)}/revoke", {}, None)

    def iam_create_access_keys(self, *, principal_type: Optional[str] = None, principal_id: Optional[str] = None, label: Optional[str] = None, expires_at: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an access key (POST /api/v1/iam/access-keys).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        principal_type: one of user, service_account"""
        payload: Dict[str, Any] = dict(json_body or {})
        if principal_type is not None:
            payload["principalType"] = principal_type
        if principal_id is not None:
            payload["principalId"] = principal_id
        if label is not None:
            payload["label"] = label
        if expires_at is not None:
            payload["expiresAt"] = expires_at
        if "principalType" not in payload:
            raise ValueError("iam_create_access_keys needs principal_type")
        if "principalId" not in payload:
            raise ValueError("iam_create_access_keys needs principal_id")
        return self._call("POST", f"/api/v1/iam/access-keys", {}, payload)

    def iam_create_groups(self, *, name: Optional[str] = None, description: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a group (POST /api/v1/iam/groups).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if description is not None:
            payload["description"] = description
        if "name" not in payload:
            raise ValueError("iam_create_groups needs name")
        return self._call("POST", f"/api/v1/iam/groups", {}, payload)

    def iam_create_groups_members(self, id_: str, *, user_id: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Members a group (POST /api/v1/iam/groups/{id}/members).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if user_id is not None:
            payload["userId"] = user_id
        if "userId" not in payload:
            raise ValueError("iam_create_groups_members needs user_id")
        return self._call("POST", f"/api/v1/iam/groups/{_q(id_)}/members", {}, payload)

    def iam_create_identity_providers(self, *, name: Optional[str] = None, type_: Optional[str] = None, metadata: Optional[Dict[str, Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an identity provider (POST /api/v1/iam/identity-providers).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        type_: one of saml, oidc"""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if type_ is not None:
            payload["type"] = type_
        if metadata is not None:
            payload["metadata"] = metadata
        if "name" not in payload:
            raise ValueError("iam_create_identity_providers needs name")
        if "type" not in payload:
            raise ValueError("iam_create_identity_providers needs type_")
        return self._call("POST", f"/api/v1/iam/identity-providers", {}, payload)

    def iam_create_invites(self, *, email: Optional[str] = None, role: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an invite (POST /api/v1/iam/invites).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        role: one of owner, admin, member"""
        payload: Dict[str, Any] = dict(json_body or {})
        if email is not None:
            payload["email"] = email
        if role is not None:
            payload["role"] = role
        if "email" not in payload:
            raise ValueError("iam_create_invites needs email")
        return self._call("POST", f"/api/v1/iam/invites", {}, payload)

    def iam_create_policies(self, *, name: Optional[str] = None, description: Optional[str] = None, document: Optional[Dict[str, Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a policy (POST /api/v1/iam/policies).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if description is not None:
            payload["description"] = description
        if document is not None:
            payload["document"] = document
        if "name" not in payload:
            raise ValueError("iam_create_policies needs name")
        if "document" not in payload:
            raise ValueError("iam_create_policies needs document")
        return self._call("POST", f"/api/v1/iam/policies", {}, payload)

    def iam_create_policy_attachments(self, *, policy_id: Optional[str] = None, principal_type: Optional[str] = None, principal_id: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a policy attachment (POST /api/v1/iam/policy-attachments).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        principal_type: one of user, group, role, service_account"""
        payload: Dict[str, Any] = dict(json_body or {})
        if policy_id is not None:
            payload["policyId"] = policy_id
        if principal_type is not None:
            payload["principalType"] = principal_type
        if principal_id is not None:
            payload["principalId"] = principal_id
        if "policyId" not in payload:
            raise ValueError("iam_create_policy_attachments needs policy_id")
        if "principalType" not in payload:
            raise ValueError("iam_create_policy_attachments needs principal_type")
        if "principalId" not in payload:
            raise ValueError("iam_create_policy_attachments needs principal_id")
        return self._call("POST", f"/api/v1/iam/policy-attachments", {}, payload)

    def iam_create_roles(self, *, name: Optional[str] = None, description: Optional[str] = None, trust_policy: Optional[Dict[str, Any]] = None, max_session_duration_sec: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a role (POST /api/v1/iam/roles).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if description is not None:
            payload["description"] = description
        if trust_policy is not None:
            payload["trustPolicy"] = trust_policy
        if max_session_duration_sec is not None:
            payload["maxSessionDurationSec"] = max_session_duration_sec
        if "name" not in payload:
            raise ValueError("iam_create_roles needs name")
        if "trustPolicy" not in payload:
            raise ValueError("iam_create_roles needs trust_policy")
        return self._call("POST", f"/api/v1/iam/roles", {}, payload)

    def iam_create_service_accounts(self, *, name: Optional[str] = None, description: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a service account (POST /api/v1/iam/service-accounts).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if description is not None:
            payload["description"] = description
        if "name" not in payload:
            raise ValueError("iam_create_service_accounts needs name")
        return self._call("POST", f"/api/v1/iam/service-accounts", {}, payload)

    def iam_create_users(self, *, email: Optional[str] = None, name: Optional[str] = None, password: Optional[str] = None, role: Optional[str] = None, email_verified: Optional[bool] = None, send_invite_email: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an user (POST /api/v1/iam/users).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        role: one of owner, admin, member"""
        payload: Dict[str, Any] = dict(json_body or {})
        if email is not None:
            payload["email"] = email
        if name is not None:
            payload["name"] = name
        if password is not None:
            payload["password"] = password
        if role is not None:
            payload["role"] = role
        if email_verified is not None:
            payload["emailVerified"] = email_verified
        if send_invite_email is not None:
            payload["sendInviteEmail"] = send_invite_email
        if "email" not in payload:
            raise ValueError("iam_create_users needs email")
        return self._call("POST", f"/api/v1/iam/users", {}, payload)

    def iam_delete_access_keys(self, id_: str) -> Any:
        """Delete an access key (DELETE /api/v1/iam/access-keys/{id})."""
        return self._call("DELETE", f"/api/v1/iam/access-keys/{_q(id_)}", {}, None)

    def iam_delete_groups(self, id_: str) -> Any:
        """Delete a group (DELETE /api/v1/iam/groups/{id})."""
        return self._call("DELETE", f"/api/v1/iam/groups/{_q(id_)}", {}, None)

    def iam_delete_groups_members(self, id_: str, user_id: str) -> Any:
        """Delete a member (DELETE /api/v1/iam/groups/{id}/members/{userId})."""
        return self._call("DELETE", f"/api/v1/iam/groups/{_q(id_)}/members/{_q(user_id)}", {}, None)

    def iam_delete_identity_providers(self, id_: str) -> Any:
        """Delete an identity provider (DELETE /api/v1/iam/identity-providers/{id})."""
        return self._call("DELETE", f"/api/v1/iam/identity-providers/{_q(id_)}", {}, None)

    def iam_delete_invites(self, id_: str) -> Any:
        """Delete an invite (DELETE /api/v1/iam/invites/{id})."""
        return self._call("DELETE", f"/api/v1/iam/invites/{_q(id_)}", {}, None)

    def iam_delete_policies(self, id_: str) -> Any:
        """Delete a policy (DELETE /api/v1/iam/policies/{id})."""
        return self._call("DELETE", f"/api/v1/iam/policies/{_q(id_)}", {}, None)

    def iam_delete_policy_attachments(self, id_: str) -> Any:
        """Delete a policy attachment (DELETE /api/v1/iam/policy-attachments/{id})."""
        return self._call("DELETE", f"/api/v1/iam/policy-attachments/{_q(id_)}", {}, None)

    def iam_delete_roles(self, id_: str) -> Any:
        """Delete a role (DELETE /api/v1/iam/roles/{id})."""
        return self._call("DELETE", f"/api/v1/iam/roles/{_q(id_)}", {}, None)

    def iam_delete_service_accounts(self, id_: str) -> Any:
        """Delete a service account (DELETE /api/v1/iam/service-accounts/{id})."""
        return self._call("DELETE", f"/api/v1/iam/service-accounts/{_q(id_)}", {}, None)

    def iam_delete_users(self, id_: str) -> Any:
        """Delete an user (DELETE /api/v1/iam/users/{id})."""
        return self._call("DELETE", f"/api/v1/iam/users/{_q(id_)}", {}, None)

    def iam_get_groups(self, id_: str) -> Any:
        """Get a group (GET /api/v1/iam/groups/{id})."""
        return self._call("GET", f"/api/v1/iam/groups/{_q(id_)}", {}, None)

    def iam_get_policies(self, id_: str) -> Any:
        """Get a policy (GET /api/v1/iam/policies/{id})."""
        return self._call("GET", f"/api/v1/iam/policies/{_q(id_)}", {}, None)

    def iam_get_roles(self, id_: str) -> Any:
        """Get a role (GET /api/v1/iam/roles/{id})."""
        return self._call("GET", f"/api/v1/iam/roles/{_q(id_)}", {}, None)

    def iam_get_service_accounts(self, id_: str) -> Any:
        """Get a service account (GET /api/v1/iam/service-accounts/{id})."""
        return self._call("GET", f"/api/v1/iam/service-accounts/{_q(id_)}", {}, None)

    def iam_groups(self) -> Any:
        """List groups (GET /api/v1/iam/groups)."""
        return self._call("GET", f"/api/v1/iam/groups", {}, None)

    def iam_identity_providers(self) -> Any:
        """List identity providers (GET /api/v1/iam/identity-providers)."""
        return self._call("GET", f"/api/v1/iam/identity-providers", {}, None)

    def iam_invites(self) -> Any:
        """List invites (GET /api/v1/iam/invites)."""
        return self._call("GET", f"/api/v1/iam/invites", {}, None)

    def iam_policies(self) -> Any:
        """List policies (GET /api/v1/iam/policies)."""
        return self._call("GET", f"/api/v1/iam/policies", {}, None)

    def iam_policy_attachments(self, *, policy_id: Optional[str] = None, principal_type: Optional[str] = None, principal_id: Optional[str] = None) -> Any:
        """List policy attachments (GET /api/v1/iam/policy-attachments)."""
        return self._call("GET", f"/api/v1/iam/policy-attachments", {"policyId": policy_id, "principalType": principal_type, "principalId": principal_id}, None)

    def iam_roles(self) -> Any:
        """List roles (GET /api/v1/iam/roles)."""
        return self._call("GET", f"/api/v1/iam/roles", {}, None)

    def iam_service_accounts(self) -> Any:
        """List service accounts (GET /api/v1/iam/service-accounts)."""
        return self._call("GET", f"/api/v1/iam/service-accounts", {}, None)

    def iam_update_identity_providers(self, id_: str, *, name: Optional[str] = None, metadata: Optional[Dict[str, Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update an identity provider (PATCH /api/v1/iam/identity-providers/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if metadata is not None:
            payload["metadata"] = metadata
        return self._call("PATCH", f"/api/v1/iam/identity-providers/{_q(id_)}", {}, payload)

    def iam_update_policies(self, id_: str, *, description: Optional[str] = None, document: Optional[Dict[str, Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a policy (PATCH /api/v1/iam/policies/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if description is not None:
            payload["description"] = description
        if document is not None:
            payload["document"] = document
        return self._call("PATCH", f"/api/v1/iam/policies/{_q(id_)}", {}, payload)

    def iam_update_users(self, id_: str, *, role: Optional[str] = None, email_verified: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update an user (PATCH /api/v1/iam/users/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        role: one of owner, admin, member"""
        payload: Dict[str, Any] = dict(json_body or {})
        if role is not None:
            payload["role"] = role
        if email_verified is not None:
            payload["emailVerified"] = email_verified
        return self._call("PATCH", f"/api/v1/iam/users/{_q(id_)}", {}, payload)

    def iam_users(self) -> Any:
        """List users (GET /api/v1/iam/users)."""
        return self._call("GET", f"/api/v1/iam/users", {}, None)

    def iam_users_reset_password(self, id_: str) -> Any:
        """Reset password an user (POST /api/v1/iam/users/{id}/reset-password)."""
        return self._call("POST", f"/api/v1/iam/users/{_q(id_)}/reset-password", {}, None)

    def mfa_challenge(self, *, token: Optional[Any] = None) -> Any:
        """Read-only — lets the standalone /mfa page render the right input (authenticator vs. emailed code) regardless of which flow created the challenge. (GET /api/v1/mfa/challenge)."""
        return self._call("GET", f"/api/v1/mfa/challenge", {"token": token}, None)

    def mfa_delete_devices(self, id_: str) -> Any:
        """Delete a device (DELETE /api/v1/mfa/devices/{id})."""
        return self._call("DELETE", f"/api/v1/mfa/devices/{_q(id_)}", {}, None)

    def mfa_devices(self) -> Any:
        """List devices (GET /api/v1/mfa/devices)."""
        return self._call("GET", f"/api/v1/mfa/devices", {}, None)

    def mfa_enroll(self, *, method: Optional[str] = None, label: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an enroll (POST /api/v1/mfa/enroll).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        method: one of totp, email"""
        payload: Dict[str, Any] = dict(json_body or {})
        if method is not None:
            payload["method"] = method
        if label is not None:
            payload["label"] = label
        return self._call("POST", f"/api/v1/mfa/enroll", {}, payload)

    def mfa_resend_code(self, *, mfa_challenge_token: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a resend code (POST /api/v1/mfa/resend-code).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if mfa_challenge_token is not None:
            payload["mfaChallengeToken"] = mfa_challenge_token
        if "mfaChallengeToken" not in payload:
            raise ValueError("mfa_resend_code needs mfa_challenge_token")
        return self._call("POST", f"/api/v1/mfa/resend-code", {}, payload)

    def mfa_resend_enrollment_code(self, *, device_id: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a resend enrollment code (POST /api/v1/mfa/resend-enrollment-code).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if device_id is not None:
            payload["deviceId"] = device_id
        if "deviceId" not in payload:
            raise ValueError("mfa_resend_enrollment_code needs device_id")
        return self._call("POST", f"/api/v1/mfa/resend-enrollment-code", {}, payload)

    def mfa_verify_enrollment(self, *, device_id: Optional[str] = None, code: Optional[str] = None, totp_code: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a verify enrollment (POST /api/v1/mfa/verify-enrollment).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if device_id is not None:
            payload["deviceId"] = device_id
        if code is not None:
            payload["code"] = code
        if totp_code is not None:
            payload["totpCode"] = totp_code
        if "deviceId" not in payload:
            raise ValueError("mfa_verify_enrollment needs device_id")
        return self._call("POST", f"/api/v1/mfa/verify-enrollment", {}, payload)

    def mfa_verify_login(self, *, mfa_challenge_token: Optional[str] = None, code: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a verify login (POST /api/v1/mfa/verify-login).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if mfa_challenge_token is not None:
            payload["mfaChallengeToken"] = mfa_challenge_token
        if code is not None:
            payload["code"] = code
        if "mfaChallengeToken" not in payload:
            raise ValueError("mfa_verify_login needs mfa_challenge_token")
        if "code" not in payload:
            raise ValueError("mfa_verify_login needs code")
        return self._call("POST", f"/api/v1/mfa/verify-login", {}, payload)

    def oidc_clients(self) -> Any:
        """List clients (GET /api/v1/oidc/clients)."""
        return self._call("GET", f"/api/v1/oidc/clients", {}, None)

    def oidc_clients_rotate_secret(self, id_: str) -> Any:
        """Rotate secret a client (POST /api/v1/oidc/clients/{id}/rotate-secret)."""
        return self._call("POST", f"/api/v1/oidc/clients/{_q(id_)}/rotate-secret", {}, None)

    def oidc_create_clients(self, *, name: Optional[str] = None, redirect_uris: Optional[List[Any]] = None, scopes: Optional[List[Any]] = None, public: Optional[bool] = None, logo_url: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a client (POST /api/v1/oidc/clients).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if redirect_uris is not None:
            payload["redirectUris"] = redirect_uris
        if scopes is not None:
            payload["scopes"] = scopes
        if public is not None:
            payload["public"] = public
        if logo_url is not None:
            payload["logoUrl"] = logo_url
        if "name" not in payload:
            raise ValueError("oidc_create_clients needs name")
        return self._call("POST", f"/api/v1/oidc/clients", {}, payload)

    def oidc_delete_clients(self, id_: str) -> Any:
        """Delete a client (DELETE /api/v1/oidc/clients/{id})."""
        return self._call("DELETE", f"/api/v1/oidc/clients/{_q(id_)}", {}, None)

    def oidc_update_clients(self, id_: str, *, name: Optional[str] = None, redirect_uris: Optional[List[Any]] = None, scopes: Optional[List[Any]] = None, logo_url: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a client (PATCH /api/v1/oidc/clients/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if redirect_uris is not None:
            payload["redirectUris"] = redirect_uris
        if scopes is not None:
            payload["scopes"] = scopes
        if logo_url is not None:
            payload["logoUrl"] = logo_url
        return self._call("PATCH", f"/api/v1/oidc/clients/{_q(id_)}", {}, payload)

    def ops_end_users(self) -> Any:
        """Workspace-scoped directory of end-users — people who have consented to an OIDC client owned by the active workspace. (GET /api/v1/ops/end-users)."""
        return self._call("GET", f"/api/v1/ops/end-users", {}, None)

    def ops_end_users_impersonate(self, id_: str, *, duration_seconds: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Impersonate an end user (POST /api/v1/ops/end-users/{id}/impersonate).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if duration_seconds is not None:
            payload["durationSeconds"] = duration_seconds
        return self._call("POST", f"/api/v1/ops/end-users/{_q(id_)}/impersonate", {}, payload)

    def ops_end_users_revoke(self, id_: str) -> Any:
        """Revoke an end user (POST /api/v1/ops/end-users/{id}/revoke)."""
        return self._call("POST", f"/api/v1/ops/end-users/{_q(id_)}/revoke", {}, None)

    def ops_end_users_send_password_reset(self, id_: str) -> Any:
        """Send password reset an end user (POST /api/v1/ops/end-users/{id}/send-password-reset)."""
        return self._call("POST", f"/api/v1/ops/end-users/{_q(id_)}/send-password-reset", {}, None)

    def ops_end_users_stop_impersonation(self) -> Any:
        """Create a stop impersonation (POST /api/v1/ops/end-users/stop-impersonation)."""
        return self._call("POST", f"/api/v1/ops/end-users/stop-impersonation", {}, None)

    def ops_end_users_verify_email(self, id_: str) -> Any:
        """Verify email an end user (POST /api/v1/ops/end-users/{id}/verify-email)."""
        return self._call("POST", f"/api/v1/ops/end-users/{_q(id_)}/verify-email", {}, None)

    def ops_get_end_users(self, id_: str) -> Any:
        """Get an end user (GET /api/v1/ops/end-users/{id})."""
        return self._call("GET", f"/api/v1/ops/end-users/{_q(id_)}", {}, None)

    def account_webhook_subscriptions_2(self, *args: Any, **kwargs: Any) -> Any:
        """Deprecated: the old name of ``account_get_webhook_subscriptions`` (GET /api/v1/account/webhook-subscriptions/{id})."""
        return self.account_get_webhook_subscriptions(*args, **kwargs)

    def iam_groups_2(self, *args: Any, **kwargs: Any) -> Any:
        """Deprecated: the old name of ``iam_get_groups`` (GET /api/v1/iam/groups/{id})."""
        return self.iam_get_groups(*args, **kwargs)

    def iam_policies_2(self, *args: Any, **kwargs: Any) -> Any:
        """Deprecated: the old name of ``iam_get_policies`` (GET /api/v1/iam/policies/{id})."""
        return self.iam_get_policies(*args, **kwargs)

    def iam_roles_2(self, *args: Any, **kwargs: Any) -> Any:
        """Deprecated: the old name of ``iam_get_roles`` (GET /api/v1/iam/roles/{id})."""
        return self.iam_get_roles(*args, **kwargs)

    def iam_service_accounts_2(self, *args: Any, **kwargs: Any) -> Any:
        """Deprecated: the old name of ``iam_get_service_accounts`` (GET /api/v1/iam/service-accounts/{id})."""
        return self.iam_get_service_accounts(*args, **kwargs)

    def ops_end_users_2(self, *args: Any, **kwargs: Any) -> Any:
        """Deprecated: the old name of ``ops_get_end_users`` (GET /api/v1/ops/end-users/{id})."""
        return self.ops_get_end_users(*args, **kwargs)


def _q(value: Any) -> str:
    from urllib.parse import quote

    return quote(str(value), safe="")
